version: "3"
services:
  csgo:
    image: "cm2network/csgo:sourcemod"
    network_mode: "host"
    volumes:
      - ./data/server:/home/steam/csgo-dedicated/
    restart: unless-stopped
    environment:
      - SRCDS_RCONPW=
      - SRCDS_PW=""
      - SRCDS_TICKRATE=64
      - SRCDS_MAXPLAYERS=64
      - SRCDS_TOKEN=yourtokenhere
      - ADDITIONAL_ARGS="+exec autoexec.cfg"







